const products=[
["YouTube Premium","Langganan","Rp 12.000","3","▶️"],["Viu Premium","Streaming","Rp 10.000","6","◉"],["HboMax Premium","Streaming","Rp 20.000","2","HBO"],["LokLok Premium","Streaming","Rp 26.000","3","🎬"],["Netflix Premium","Streaming","Rp 28.500","3","N"],["Disney+ Premium","Streaming","Rp 27.000","3","✦"],["Canva Premium","Editing","Rp 10.000","4","Canva"],["Meitu+ Premium","Editing","Rp 20.000","3","M"],["Wink+ Premium","Editing","Rp 20.000","3","✦"],["Picsart Premium","Editing","Rp 15.000","4","P"],["iQIYI Premium","Streaming","Rp 23.000","3","iQ"],["Spotify Premium","Music","Rp 15.000","3","♫"],["CapCut Pro","Editing","Rp 18.000","3","✂"],["Vidio Platinum","Streaming","Rp 22.000","3","V"],["ChatGPT Plus","Other","Rp 20.000","2","AI"],["Disney+ Hotstar","Streaming","Rp 25.000","3","✦"],["YouTube Music","Music","Rp 18.000","3","♫"],["Grammarly Premium","Other","Rp 20.000","2","G"],["Prime Video","Streaming","Rp 18.000","3","▶"],["Apple Music","Music","Rp 20.000","3","♫"],["Alight Motion","Editing","Rp 15.000","3","A"],["Picsart Gold","Editing","Rp 18.000","3","P"],["Gemini AI","Other","Rp 25.000","2","✦"],["Canva Pro Lifetime","Editing","Rp 30.000","1","Canva"],["Roblox Premium","game","Rp 20.000","3","R"]];
let cart=JSON.parse(localStorage.getItem("lilac_cart")||"[]");
const productsEl=document.getElementById("products"), search=document.getElementById("search");
function render(cat="Semua",q=""){productsEl.innerHTML="";products.filter(p=>(cat==="Semua"||p[1]===cat)&&p[0].toLowerCase().includes(q.toLowerCase())).forEach((p,i)=>{const c=document.createElement("article");c.className="card";c.innerHTML=`<span class="tag">▣ ${p[1]}</span><span class="heart">♥</span><div class="thumb"><div class="iconbox ${i===0?"yt":""}">${p[4]}</div></div><h3>${p[0]}</h3><p class="price">Mulai ${p[2]}</p><div class="variant">Tersedia (${p[3]} varian)</div><button class="buy" data-i="${i}">Beli Sekarang　✦</button>`;productsEl.appendChild(c)})}
function updateCart(){document.getElementById("cartCount").textContent=cart.length;document.getElementById("cartCountTop").textContent=cart.length;localStorage.setItem("lilac_cart",JSON.stringify(cart))}
document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{document.querySelectorAll(".cat").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.cat,search.value)});
search.oninput=()=>{const a=document.querySelector(".cat.active");render(a?.dataset.cat||"Semua",search.value)};
productsEl.onclick=e=>{const b=e.target.closest(".buy");if(!b)return;cart.push(products[+b.dataset.i]);updateCart();openCart()};
function openCart(){document.getElementById("modalContent").innerHTML=`<h2>🛍️ Keranjang (${cart.length})</h2>${cart.length?cart.map((p,i)=>`<p><b>${i+1}. ${p[0]}</b> — ${p[2]}</p>`).join(""):`<p>Keranjang masih kosong.</p>`}<button class="action" onclick="checkout()">Lanjut Checkout</button>`;document.getElementById("modal").classList.add("show")}
function checkout(){const text=cart.map(p=>`- ${p[0]} (${p[2]})`).join("%0A");const msg=`Halo Lilacmart, saya ingin order:%0A${text}%0A%0ATotal item: ${cart.length}`;window.open("https://wa.me/628xxxxxxxxxx?text="+msg,"_blank")}
document.getElementById("cartFloat").onclick=openCart;document.getElementById("cartTop").onclick=openCart;document.getElementById("close").onclick=()=>document.getElementById("modal").classList.remove("show");document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")e.currentTarget.classList.remove("show")};
render();updateCart();